# Generated by Django 5.2.6 on 2025-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.AlterField(
            model_name='deliveryzones',
            name='min_delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='options',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
