# Generated by Django 5.2.6 on 2025-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='orderitemoptions',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='promos',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
